services:
  bitbag_sylius_multi_cart_plugin.event_listener.machine_id:
    class: BitBag\SyliusMultiCartPlugin\EventListener\MachineIdListener
    arguments:
      - '@bitbag_sylius_multi_cart_plugin.context.cookie'
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'checkCookie', priority: 1000 }
      - { name: 'kernel.event_listener', event: 'kernel.response', method: 'setCookie', priority: 1000 }

  BitBag\SyliusMultiCartPlugin\EventListener\ShopCartBlamerListener:
    decorates: 'sylius.listener.shop_cart_blamer'
    arguments:
      - '@BitBag\SyliusMultiCartPlugin\EventListener\ShopCartBlamerListener.inner'
      - '@sylius.context.cart'
      - '@sylius.section_resolver.uri_based_section_resolver'
      - '@sylius.repository.order'
      - '@sylius.context.channel'
      - '@bitbag_sylius_multi_cart_plugin.context.cookie'
      - '%allow_multicart_for_anonymous%'
    tags:
      - { name: 'kernel.event_listener', event: 'sylius.user.security.implicit_login', method: 'onImplicitLogin' }
      - { name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onInteractiveLogin' }
